# Configuracion segura para produccion
# Sin interfaz visual pero con la documentacion JSON para herramientas externas
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=true

# Seguridad adicional: no exponer endpoints internos
springdoc.paths-to-exclude=/admin/**,/internal/**
